# Generated by Django 5.0.6 on 2024-05-25 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'End User',
                'verbose_name_plural': 'End Users',
            },
            bases=('users.customuser',),
        ),
        migrations.CreateModel(
            name='ManagerUser',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manager User',
                'verbose_name_plural': 'Manager Users',
            },
            bases=('users.customuser',),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
    ]
